apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: stage
  labels:
    app: order-service
    environment: stage
spec:
  type: NodePort
  selector:
    app: order-service
  ports:
  - name: http
    protocol: TCP
    port: 8300
    targetPort: 8300
    nodePort: 30300
