apiVersion: v1
kind: ConfigMap
metadata:
  name: micro-config
  namespace: stage
  labels:
    environment: stage
    managed-by: jenkins
data:
  # Spring Profile
  SPRING_PROFILES_ACTIVE: "stage"
  
  # JVM Options - Stage Environment
  JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
  
  # Service Discovery (Eureka)
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://service-discovery.stage.svc.cluster.local:8761/eureka/"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  EUREKA_INSTANCE_HOSTNAME: "${spring.application.name}.stage.svc.cluster.local"
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_FETCH_REGISTRY: "true"
  
  # Zipkin Tracing
  SPRING_ZIPKIN_BASE_URL: "http://zipkin.stage.svc.cluster.local:9411/"
  SPRING_SLEUTH_SAMPLER_PROBABILITY: "0.3"
  
  # Service URLs (Internal Communication)
  USER_SERVICE_HOST: "http://user-service.stage.svc.cluster.local:8700"
  PRODUCT_SERVICE_HOST: "http://product-service.stage.svc.cluster.local:8500"
  FAVOURITE_SERVICE_HOST: "http://favourite-service.stage.svc.cluster.local:8400"
  PROXY_CLIENT_HOST: "http://proxy-client.stage.svc.cluster.local:8900"
  API_GATEWAY_HOST: "http://api-gateway.stage.svc.cluster.local:9000"
  
  # Logging
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_SELIMHORRI: "INFO"
  
  # Management & Actuator
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "when-authorized"
  # Spring Config Server
  SPRING_CONFIG_IMPORT: "configserver:http://cloud-config.stage.svc.cluster.local:9296/"

