apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  namespace: stage
  labels:
    app: proxy-client
    environment: stage
spec:
  type: ClusterIP
  selector:
    app: proxy-client
  ports:
  - name: http
    protocol: TCP
    port: 8900
    targetPort: 8900

