apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
  namespace: stage
  labels:
    app: cloud-config
    environment: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
        environment: stage
    spec:
      containers:
        - name: cloud-config
          image: ecommerce/cloud-config:stage-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9296
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: micro-config
                  key: SPRING_PROFILES_ACTIVE
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "192Mi"
              cpu: "100m"
            failureThreshold: 3
