apiVersion: v1
kind: Service
metadata:
  name: cloud-config
  namespace: stage
  labels:
    app: cloud-config
    environment: stage
spec:
  type: ClusterIP
  selector:
    app: cloud-config
  ports:
  - name: http
    protocol: TCP
    port: 9296
    targetPort: 9296

