server:
  port: 8700

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

spring:
  # config:
  #   import: "" # Deshabilitar cloud-config
  cloud:
    # config:
    #   enabled: false
    discovery:
      client:
        simple:
          enabled: true
  zipkin:
    enabled: false
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: WARN
    com.selimhorri: INFO