apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: stage
  labels:
    app: product-service
    environment: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
        environment: stage
    spec:
      containers:
      - name: product-service
        image: ecommerce/product-service:stage-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8500
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "stage"
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8500
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8500
          initialDelaySeconds: 120
          periodSeconds: 5
          failureThreshold: 10
