apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: stage
  labels:
    app: product-service
    environment: stage
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
  - name: http
    protocol: TCP
    port: 8500
    targetPort: 8500
    nodePort: 30500
