apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: stage
  labels:
    app: api-gateway
    environment: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        environment: stage
    spec:
      containers:
        - name: api-gateway
          image: ecommerce/api-gateway:stage-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: micro-config
                  key: SPRING_PROFILES_ACTIVE
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: micro-config
                  key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
            - name: USER_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: micro-config
                  key: USER_SERVICE_HOST
            - name: PRODUCT_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: micro-config
                  key: PRODUCT_SERVICE_HOST
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "192Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9000
            initialDelaySeconds: 45
            periodSeconds: 5
            failureThreshold: 3
