apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: stage
  labels:
    app: service-discovery
    environment: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
        environment: stage
    spec:
      containers:
        - name: service-discovery
          image: ecommerce/service-discovery:stage-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: micro-config
                  key: SPRING_PROFILES_ACTIVE
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "192Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 45
            periodSeconds: 5
            failureThreshold: 3
