apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: production
  labels:
    app: service-discovery
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
        env: production
    spec:
      containers:
        - name: service-discovery
          image: ecommerce/service-discovery:prod-latest
          ports:
            - containerPort: 8761
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 30
