apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: stage
  labels:
    app: service-discovery
    environment: stage
spec:
  type: ClusterIP
  selector:
    app: service-discovery
  ports:
  - name: http
    protocol: TCP
    port: 8761
    targetPort: 8761

