apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: stage
  labels:
    app: user-service
    environment: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        environment: stage
    spec:
      containers:
      - name: user-service
        image: ecommerce/user-service:stage-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8700
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "stage"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "192Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8700
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8700
          initialDelaySeconds: 45
          periodSeconds: 5
          failureThreshold: 3
