apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: stage
  labels:
    app: user-service
    environment: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        environment: stage
    spec:
      containers:
      - name: user-service
        image: ecommerce/user-service:stage-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8700
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "stage"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8700
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8700
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
