apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: stage
  labels:
    app: user-service
    environment: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        environment: stage
    spec:
      containers:
      - name: user-service
        image: ecommerce/user-service:stage-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8700
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        - name: PRODUCT_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: PRODUCT_SERVICE_HOST
        - name: SPRING_CONFIG_IMPORT
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: SPRING_CONFIG_IMPORT
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "768Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8700
          initialDelaySeconds: 120
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8700
          initialDelaySeconds: 90
          periodSeconds: 5
          failureThreshold: 3
