apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: stage
  labels:
    app: user-service
    environment: stage
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
  - name: http
    protocol: TCP
    port: 8700
    targetPort: 8700
    nodePort: 30700
